<?php

/**
 * @file
 * Twitter module hooks.
 */

/**
 * Implements hook_theme().
 */
function twitter_feed_theme($existing, $type, $theme, $path) {
  return [
    'twitter_feed_item' => [
      'template' => 'twitter-feed-item',
      'variables' => array('tweet' => NULL),
    ],
  ];
}

/**
 * Implements hook_libraries_info().
 */
function twitter_feed_libraries_info() {
  $libraries['timeago'] = array(
    'name' => 'TimeAgo',
    'vendor url' => 'http://timeago.yarp.com',
    'download url' => 'https://github.com/rmm5t/jquery-timeago/zipball/v1.5.2',
    'version arguments' => array(
      'file' => 'jquery.timeago.js',
      // @version 1.5.2
      'pattern' => '@version\s+([0-9a-zA-Z\.-]+)@',
      'lines' => 10,
    ),
    'files' => array(
      'js' => array(
        'jquery.timeago.js',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_library_info_build().
 *
 * We also define Timeago through the core library callbacks.
 */
function twitter_feed_library_info_build() {
  $lib = twitter_feed_libraries_info();
  $libraries = [];

  $library_path = libraries_get_path('timeago');
  if (strpos($library_path, '/') !== 0) {
    $library_path = '/' . $library_path;
  }

  $libraries['timeago'] = array(
    'title' => $lib['timeago']['name'],
    'remote' => $lib['timeago']['vendor url'],
    'version' => '1.5.2',
    'license' => array(
      'name' => 'MIT',
      'url' => 'https://github.com/rmm5t/jquery-timeago/raw/master/LICENSE.txt',
      'gpl-compatible' => TRUE,
    ),
    'dependencies' => array(
      'core/jquery',
    ),
    'js' => array(
      $library_path . '/jquery.timeago.js' => array(
        'scope' => 'footer',
      ),
    ),
  );

  $languages = twitter_feed_timeago_languages();
  foreach ($languages as $language_name) {
    $libraries['timeago_' . $language_name] = [
      'title' => $lib['timeago']['name'],
      'remote' => $lib['timeago']['vendor url'],
      'version' => '1.5.2',
      'license' => [
        'name' => 'MIT',
        'url' => 'https://github.com/rmm5t/jquery-timeago/raw/master/LICENSE.txt',
        'gpl-compatible' => TRUE,
      ],
      'dependencies' => [
        'core/jquery',
      ],
      'js' => [
        $library_path . '/locales/jquery.timeago.' . $language_name . '.js' => [
          'scope' => 'footer',
        ],
      ],
    ];
  }

  return $libraries;
}

/**
 * Get timeago languages.
 *
 * @return array
 */
function twitter_feed_timeago_languages() {
  $path = libraries_get_path('timeago');
  $files = file_scan_directory("$path/locales", '/timeago\..{2,14}\.js$/i', ['recurse' => FALSE, 'key' => 'name']);
  $timeago_locales = [];
  if ($files) {
    foreach ($files as $name => $file) {
      preg_match('/timeago\.(.{2,14})$/i', $name, $matches);
      if ($matches[1]) {
        $timeago_locales[$matches[1]] = $matches[1];
      }
    }
  }
  ksort($timeago_locales);

  return $timeago_locales;
}

/**
 * Implements hook_preprocess_twitter_feed_item().
 */
function template_preprocess_twitter_feed_item(&$vars) {
  $tweet = $vars['tweet'];
  // Creates a fake input_format so we can use some internal Drupal filters.
  $fake_filter = new stdClass();
  $fake_filter->settings = ['filter_url_length' => 72];
  // Converts URLs to links and line-breaks to paragraphs.
  // TODO hashtags and usernames.
  $vars['text'] = ['#markup' => _filter_autop(_filter_url($tweet->text, $fake_filter))];
  // This is the datestamp that jQuery timeago expects.
  $vars['date']['stamp'] = date('c', strtotime($tweet->created_at));
  $vars['date']['clean'] = \Drupal::service('date.formatter')->format(strtotime($tweet->created_at), 'short');
}
